### ISSUE TITLE
Error in Docker

### ISSUE THREAD

**Issue by rezzalex** [bazwilliams/domoticz-sound-detection#2]
Hello. Thnaks for your software and your docker container.
After pulling the latest image and launch it with portainer, includeing the environnement variable, here is my Log : 

"
npm ERR! There is likely additional logging output above.,
,
npm ERR! Please include the following file with any support request:,
npm ERR!     /usr/src/app/npm-debug.log,
npm info it worked if it ends with ok,
npm info using npm@2.15.9,
m info using node@v4.5.0,
npm info prestart domoticz-sound-detection@0.0.2,
npm info start domoticz-sound-detection@0.0.2,
,
> domoticz-sound-detection@0.0.2 start /usr/src/app,
> node ./app.js,
,
buffer.js:680,
    throw new RangeError('index out of range');,
    ^,
,
RangeError: index out of range,
    at checkOffset (buffer.js:680:11),
    at Buffer.readInt16LE (buffer.js:815:5),
    at null._decoder (/usr/src/app/node_modules/sound-detection/node_modules/pcm-boilerplate/lib/utils.js:89:38),
    at _.extend.read (/usr/src/app/node_modules/sound-detection/node_modules/pcm-boilerplate/lib/utils.js:34:33),
    at processBlock (/usr/src/app/node_modules/sound-detection/index.js:16:35),
    at emitNone (events.js:67:13),
    at emit (events.js:166:7),
    at emitReadable_ (_stream_readable.js:419:10),
    at emitReadable (_stream_readable.js:413:7),
    at readableAddChunk (_stream_readable.js:164:13),
,
npm info domoticz-sound-detection@0.0.2 Failed to exec start script,
npm ERR! Linux 4.14.x,
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "start",
npm ERR! node v4.5.0,
npm ERR! npm  v2.15.9,
npm ERR! code ELIFECYCLE,
npm ERR! domoticz-sound-detection@0.0.2 start: `node ./app.js`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the domoticz-sound-detection@0.0.2 start script 'node ./app.js'.,
npm ERR! This is most likely a problem with the domoticz-sound-detection package,,
npm ERR! not with npm itself.,
npm ERR! Tell the author that this fails on your system:,
m ERR!     node ./app.js,
npm ERR! You can get information on how to open an issue for this project with:,
npm ERR!     npm bugs domoticz-sound-detection,
npm ERR! Or if that isn't available, you can get their info via:,,
 ,
npm ERR!     npm owner ls domoticz-sound-detection,
npm ERR! There is likely additional logging output above.,
,
npm ERR! Please include the following file with any support request:,
npm ERR!     /usr/src/app/npm-debug.log,
npm info it worked if it ends with ok,
npm info using npm@2.15.9,
m info using node@v4.5.0,
npm info prestart domoticz-sound-detection@0.0.2,
npm info start domoticz-sound-detection@0.0.2,
,
> domoticz-sound-detection@0.0.2 start /usr/src/app,
> node ./app.js,
,
buffer.js:680,
    throw new RangeError('index out of range');,
    ^,
,
RangeError: index out of range,
    at checkOffset (buffer.js:680:11),
    at Buffer.readInt16LE (buffer.js:815:5),
    at null._decoder (/usr/src/app/node_modules/sound-detection/node_modules/pcm-boilerplate/lib/utils.js:89:38),
    at _.extend.read (/usr/src/app/node_modules/sound-detection/node_modules/pcm-boilerplate/lib/utils.js:34:33),
    at processBlock (/usr/src/app/node_modules/sound-detection/index.js:16:35),
    at emitNone (events.js:67:13),
    at emit (events.js:166:7),
    at emitReadable_ (_stream_readable.js:419:10),
    at emitReadable (_stream_readable.js:413:7),
    at readableAddChunk (_stream_readable.js:164:13),
,
npm info domoticz-sound-detection@0.0.2 Failed to exec start script,
npm ERR! Linux 4.14.x,
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "start",
npm ERR! node v4.5.0,
npm ERR! npm  v2.15.9,
npm ERR! code ELIFECYCLE,
npm ERR! domoticz-sound-detection@0.0.2 start: `node ./app.js`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the domoticz-sound-detection@0.0.2 start script 'node ./app.js'.,
npm ERR! This is most likely a problem with the domoticz-sound-detection package,,
npm ERR! not with npm itself.,
npm ERR! Tell the author that this fails on your system:,
m ERR!     node ./app.js,
npm ERR! You can get information on how to open an issue for this project with:,
npm ERR!     npm bugs domoticz-sound-detection,
npm ERR! Or if that isn't available, you can get their info via:,,
 ,
npm ERR!     npm owner ls domoticz-sound-detection,
npm ERR! There is likely additional logging output above.,
,
npm ERR! Please include the following file with any support request:,
npm ERR!     /usr/src/app/npm-debug.log,
"

What did I missed ?

Thanks

RezzA

**Comment by rezzalex** [comment]
Hello @bazwilliams , Any update ?

**Comment by bazwilliams** [comment]
Hi 👋 

Sorry notifications are off on this repo. Can you share the command you use to run it please and a link to the camera you’re using?

thanks

**Comment by rezzalex** [comment]
Hello,

when trying to answer you, I disovered that there was a space in my Cam audio stream URL .... 
Now it works ! thanks
I did not specified any of those parameters : BITDEPTH, CHANNELS, TRIGGERLEVEL

and the result is that I have to shout very close to the camera to trigger the detector,
I have a D-Link DCS-800L, what could you recommend to increase the detection threshold ?

thanks for your work

**Comment by bazwilliams** [comment]
The trigger level defines how many dB above ambient before It triggers. 

The default is 30. Try reducing to 0 and increasing it until you get the value right. 

The “ambient level” is adaptive so if the background noise increases so will the threshold to trigger.

**Comment by rezzalex** [comment]
thanks a lot
